{% set name = "Orange3-Explain" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c80d96bb52ff0a7f81eae218838144300b6c3e318b4bd839246d6bcdfe36ba76

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - Orange3 >=3.27.1
    - orange-widget-base
    - AnyQt
    - numpy
    - pyqtgraph
    - scipy
    - shap ==0.37.*

test:
  imports:
    - orangecontrib.explain

about:
  home: https://github.com/biolab/orange3-explain
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Explainable AI add-on for Orange3
  description: |
    Orange3 Explain is an add-on for the Orange3 data mining suite. 
    It provides extensions for explanatory AI.
  doc_url: http://orange3-explain.readthedocs.io/
  dev_url: https://github.com/biolab/orange3-explain

extra:
  recipe-maintainers:
    - PrimozGodec
    - VesnaT
